export { AboutSection } from "./about-section"
export { FooterContent } from "./footer-content"
export { TrustBadges } from "./trust-badges"
export { FooterBottom } from "./footer-bottom"
export { CompanyColumn } from "./company-column"
export { SupportColumn } from "./support-column"
export { CompanyResourcesColumn } from "./company-resources-column"
export { QuickLinksColumn } from "./quick-links-column"
export { PoliciesSocialColumn } from "./policies-social-column"
export { SocialIcons } from "./social-icons"

